### PR TITLE
Upgrade to v14

### LINKED ISSUE #396: Add homepage in package.json
Please add `homepage` in **package.json** and maybe some other usefull data like `bugs`, `licence`, `description`...

https://docs.npmjs.com/cli/v8/configuring-npm/package-json

### LINKED ISSUE #404: Angular 14
Hi, any chance to update the library to Angular 14 please?

### PR DESCRIPTION
**Pull request by leonardssh**
This PR aims to upgrade the library to support Angular v14.

Resolves #404
Resolves #396

### CODE REVIEW

**Comment by shyamal890** [comment]
When would this be published?

**Comment by orizens** [comment]
soon

**Comment by roldengarm** [comment]
Thank you for this awesome library! It was very easy to implement. We're just upgrading to Angular 14 and ngx-infinite-scroll is the last library that's not compatible yet. Hopefully it can be released soon 👍

**Comment by orizens** [comment]
thanks @leonardssh 
i had to rebase and update the branch at #406

**Pull request closed without merging**
