### PR TITLE
Watch for changes in infiniteScrollDistance prop

### PR DESCRIPTION
**Pull request by WandersonAlves**
Why? I need to trigger a event in a certain area of the screen. Using a fixed value, as the screen goes bigger, the area will change. To fix that, i use a dynamic prop to set the proper infiniteScrollDistance based on a certain thing.

Version: 0.6.1

### CODE REVIEW

**Comment by orizens** [comment]
hi @WandersonAlves 
#196 already started handling this.

**Comment by WandersonAlves** [comment]
#196 is about infiniteScrollDisabled no?

**Comment by orizens** [comment]
yes - my mistake.
since this prop is changed from the outside of this component - this logic isn't part of this component.
i'll look into it.

**Comment by WandersonAlves** [comment]
Any updates?

**Comment by orizens** [comment]
not yet - have a busy project - this will have to wait for few more days now.

**Comment by orizens** [comment]
@WandersonAlves  thanks.

**Pull request merged**
