### PR TITLE
feat: update to angular 9

### PR DESCRIPTION
**Pull request by santoshyadav198613**
A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. 

**Summary**

This PR fixes/implements the following **bugs/features**

- [x] update to Angular v9
- [ ] Breaking changes

### CODE REVIEW

**Comment by orizens** [comment]
@santoshyadav198613 thanks for raising this pr. is that ready for review?

**Comment by santoshyadav198613** [comment]
Hi @orizens ,
This is ready for review now.

**Comment by orizens** [comment]
@santoshyadav198613 have you verified unit tests are passing?

**Comment by santoshyadav198613** [comment]
image
yes working can you add github action so it can be verified on each pull request

**Comment by orizens** [comment]
travis build was failing. i fixed it. should be good now.

**Comment by orizens** [comment]
@santoshyadav198613 can you advice: should there be any breaking changes?

**Comment by santoshyadav198613** [comment]
> @santoshyadav198613 can you advice: should there be any breaking changes?

No breaking changes the updated should be smooth.

**Comment by santoshyadav198613** [comment]
Hi @orizens ,
Can we merge this?

**Comment by orizens** [comment]
thanks @santoshyadav198613 
v9.0.0 is live now.

**Pull request merged**
