### PR TITLE
Use opencollective-postinstall instead of opencollective

### PR DESCRIPTION
**Pull request by topaxi**
**Summary**

Use opencollective-postinstall instead of opencollective

Explain the **motivation** for making this change. What existing problem does the pull request solve?

See https://github.com/orizens/ngx-infinite-scroll/pull/231#issuecomment-381630254

### Requirements
Make sure these boxes are checked:  
- [x] link to an issue
- [x] tests are updated (added/changed/removed)  
- [x] tests run successfully (local) 
- [x] tests run successfully (TravisCI) 
- [x] please follow this [styleguide](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#subject-line) for this pr title

### CODE REVIEW

**Comment by mnahkies** [comment]
@topaxi wouldn't these be shaken out of production builds anyway? Still not ideal, but I wouldn't have expected it to affect bundle sizes

**Comment by topaxi** [comment]
This wasn't about bundle size but installation size. Sometimes one is on the road and wants to develop and being in a train or on some bad mobile or wifi connection the size of packages and amount of dependencies can cripple local installation with `npm install` a lot.

**Comment by anteq** [comment]
Hey, how about substituting `opencollective postinstall` with `opencollective-postinstall`? It looks like it's the new recommended package with almost no dependencies. That also prevents "Permission denied" crashes on some CI servers:
https://github.com/opencollective/opencollective-postinstall/issues/15

**Comment by topaxi** [comment]
I have updated the PR to use `opencollective-postinstall`.

**Pull request merged**
